name: CI/CD auto deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI : ${{ secrets.mongodb_uri }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build Number
        id: build-number
        run: echo "::save-state name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Echo MONGODB_URI
        run: echo $MONGODB_URI
      - name: Build with Maven
        run: mvn -B package --file pom.xml
